name: Build and Run Docker Compose Stack

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build & Run Compose Stack
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean up old containers
        run: |
          docker compose -f ./docker-compose-example.yaml down

      - name: Build all services (no cache) and start stack detached
        run: |
          docker compose -f ./docker-compose-example.yaml up -d --build

      - name: Check running containers
        run: |
          docker ps -a
