name: Build and Run Docker Compose Stack

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-run:
    name: Build & Run Compose Stack
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Update services
        run: |
          docker compose -f ./docker-compose-example.yaml up -d --build --remove-orphans

      - name: Cleanup old images
        run: |
          # Removes dangling images left over from the build process
          docker image prune -f
